spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://106.14.253.101:3306/course_system
    username: root
    password: Tongji@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 自动更新数据库表结构
    show-sql: true       # 显示SQL语句
    properties:
      hibernate:
        format_sql: true # 格式化SQL输出
  web:
    cors:
      mappings:
        # 匹配路径
        "/**":
          # 允许的来源
          allowed-origins: "*"
          # 允许的方法
          allowed-methods: "*"
          # 允许的头
          allowed-headers: "*"
          # 是否允许凭据（Cookie）
          allow-credentials: true
          # 预检请求的缓存时间（秒）
          max-age: 3600
server:
  port: 8080
# JWT 配置
jwt:
  secret: course_system
  expiration-time: 86400000 # 令牌有效时间，单位为毫秒
  header: Authorization # JWT 令牌的请求头
  prefix: Bearer # 令牌前缀
